# Generated by Django 4.2.5 on 2023-09-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='secondLastName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='secondName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
