# Generated by Django 4.2.5 on 2023-10-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_name', models.CharField(max_length=100)),
                ('per_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='role',
            old_name='description',
            new_name='role_description',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='name',
            new_name='role_name',
        ),
    ]
